# mm-address/docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres  # The initial database to connect to
      POSTGRES_USER: marketmaster
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/mm-address.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  address_service:
    build: .  # Build context set to project root
    ports:
      - "5700:5700"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - .:/app  # Map the project root to /app in the container

volumes:
  postgres_data:
